word_list = ['abecedar',
             'banana',
             'farfurie',
             'pantof',
             'palarie',
             'cascada',
             'televizor',
             'masina',
             'pensiune',
             'muzica',
             'cartof',
             'tricou',
             'verde',
             'administrativ',
             'trichineloza',
             'comunicativilor',]
